# https://docs.github.com/en/actions/tutorials/build-and-test-code/nodejs
# https://github.com/actions/setup-node

name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglx-dev libx11-dev libxext-dev libxi-dev
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
